# Generated by Django 5.0.6 on 2024-07-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='Blog_post_publish_3fcdce_idx',
        ),
    ]
